### ISSUE TITLE
ResponseClass hata dönüşü

### ISSUE THREAD

**Issue by onurryildirimm** [slvler/posnet-payment-service#1]
![posnethata](https://user-images.githubusercontent.com/119333026/204302596-c75affb8-845d-474e-9dfc-fc454d85e16c.png)

Request attıktan sonra bu hatalar dönüyor sebebi neyden kaynaklıdır acaba ?

**Comment by selviler** [comment]
slvler@proton.me adresine yazabilirsiniz.
